version: "3.9"
services:
  frontend:
    image: kanut-client:v1
    container_name: kanut-client-container
    build: 
      context: .
      dockerfile: Dockerfile
    # command: npm run dev
    ports:
      - "3001:3001"
    volumes:
      - app-storage:/app
      - node_modules:/app/node_modules
volumes:
  app-storage: {}
  node_modules: {}